spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://schema-db.crturo38jtgq.ap-northeast-2.rds.amazonaws.com:8080/schema_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: schema_master
    password: schema123!

  jwt:
    secret: jwtsecretkey

  jpa:
    hibernate:
      #옵션 create, update, none, create-drop, validate 있음
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:hibernate:SQL: DEBUG